version: '3'
services: 
  app-dev: 
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     NODE_ENV: production
    # image: food-friend-server
    image: node:8.9.2
    working_dir: /opt/app
    command: ["./wait-for-it.sh", "db:5432", "--", "./run-dev.sh"]
    environment:
      PORT: 3000
      VIRTUAL_HOST: vteam.dev
      VIRTUAL_PORT: 3000
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env.example
    ports:
      - "3000"
      - "8080"
    depends_on:
      - db-dev
    links:
      - db-dev:db
    volumes:
      - .:/opt/app
    restart: unless-stopped
    network_mode: bridge
  db-dev:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123@@
      POSTGRES_DB: food-friend-dev
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
volumes:
  db:
